# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3880bf95287695509eaf340ce49410cae8cb9feb69a3dab1cc50cd444a9138d1b0acf4707b2e455b959358d184f63773f25ac92718f7e8f3619627648991c2a7

test:
  secret_key_base: 8ae2177a5ff966d6e979972be8b09497208d6cec4e74273378dd687635a84393ec4a25cc73ba736a93f1e443f60fbfeeb3f48b6b213d2768e793c40aa57e5545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
